# dashboard/app.py
"""
Pipeline Leak Risk Management Streamlit Executive Command Center.
Visualizes 11-modal sensor fusion, Geospatial Risk Heatmap, Multi-Agent SCADA actions, 
and automated SAP/Maximo Work Orders.
"""

import os
import json
import requests
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import numpy as np

# ==============================================================================
# 1. Configuration & Theme
# ==============================================================================
st.set_page_config(page_title="Pipeline Leak Risk Management Executive Command Center", layout="wide", page_icon="🛢️")

# Custom CSS for Dark "Control Room" Theme
st.markdown("""
    <style>
    .main { background-color: #0e1117; color: #ffffff; }
    .sidebar .sidebar-content { background-color: #161b22; }
    h1, h2, h3 { color: #ffffff; }
    div[data-testid="stMetricValue"] { font-size: 2rem; }
    </style>
""", unsafe_allow_html=True)

st.title("🛢️ Pipeline Leak Risk Management Executive Command Center")
st.markdown("Powered by **Nebius AI Cloud** | Edge Fusion: **Jetson Orin** | LLM: **Nemotron 3 Super** | EAM: **SAP/Maximo**")

API_BASE_URL = "http://localhost:8000"

# ==============================================================================
# 2. Data Fetching (API with Mock Fallback)
# ==============================================================================
def fetch_data():
    """Fetches data from API, falls back to local JSON, then to mock data."""
    alerts, scada_logs, risk_data = [], [], []
    
    try:
        # Try fetching from API
        resp_alerts = requests.get(f"{API_BASE_URL}/api/v1/risk/nodes", timeout=2) # Using risk endpoint to check API
        # In a real app, we'd have specific endpoints for alerts/logs. 
        # For this prototype, we read the local files generated by the API.
    except:
        pass

    # Read local files generated by the API
    data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../data'))
    
    def load_json(filename):
        path = os.path.join(data_dir, filename)
        if os.path.exists(path):
            with open(path, "r") as f:
                try: return json.load(f)
                except: return []
        return []

    alerts = load_json("alerts.json")
    scada_logs = load_json("scada_logs.json")
    risk_data = load_json("risk_assessments.json")
    
    # If completely empty, generate mock data for the demo
    if not alerts and not risk_data:
        st.toast("API offline. Loading Executive Mock Data...", icon="⚠️")
        # Mock Risk Data for Heatmap
        np.random.seed(42)
        for i in range(25):
            pof = np.random.uniform(70, 95) if 14 <= i <= 17 else np.random.uniform(5, 25)
            cof = np.random.uniform(80, 100) if 14 <= i <= 17 else np.random.uniform(10, 40)
            dri = (pof * cof) / 100.0
            tier = "CRITICAL" if dri >= 75 else "LOW"
            risk_data.append({
                "node_id": f"NODE-{100+i}", "lat": 31.99 - (i*0.1), "lon": -102.07 + (i*0.3),
                "pof": pof, "cof": cof, "dynamic_risk_index": dri, "risk_tier": tier,
                "mitigation_plan": [f"Tier {tier} protocol active."] if tier == "CRITICAL" else ["Standard monitoring."]
            })
            
    return alerts, scada_logs, risk_data

alerts, scada_logs, risk_data = fetch_data()

# ==============================================================================
# 3. Sidebar Metrics
# ==============================================================================
st.sidebar.header("📊 Network Summary")
st.sidebar.metric("Total Pipeline Nodes", 25)
st.sidebar.metric("Active Edge Nodes", 142, delta="Federated Learning")

critical_risks = sum(1 for r in risk_data if r.get("risk_tier") == "CRITICAL")
st.sidebar.metric("Critical Risk Nodes", critical_risks, delta="⚠️ Action Required" if critical_risks > 0 else "✅ Secure")

active_work_orders = sum(1 for r in risk_data if "work_order" in r)
st.sidebar.metric("Auto-Generated Work Orders", active_work_orders)

st.sidebar.divider()
st.sidebar.subheader("🧠 Federated Learning")
st.sidebar.metric("Global Model Version", "v2.4.1")
st.sidebar.metric("Total FL Rounds", 847)
st.sidebar.caption("Data remains on-premises. Only encrypted weight deltas transmitted.")

# ==============================================================================
# 4. Main Layout: Tabbed Interface
# ==============================================================================
tab_ops, tab_risk, tab_eam = st.tabs(["📡 Operational Control", "️ Executive Risk Heatmap", "️ Autonomous Actions & EAM"])

# --- TAB 1: Operational Control ---
with tab_ops:
    col1, col2 = st.columns([2, 1])
    with col1:
        st.subheader(" Live Event Log")
        if alerts:
            df_data = [{"Time": a["payload"]["timestamp"][:19], "Node": a["payload"]["node_id"], 
                        "Decision": a["payload"]["decision"], "Confidence": f"{a['payload']['final_confidence']*100:.1f}%"} 
                       for a in reversed(alerts)]
            st.dataframe(pd.DataFrame(df_data), use_container_width=True, hide_index=True)
        else:
            st.info("Waiting for edge alerts...")

        st.subheader("️ 11-Modal Sensor Fusion Analysis (Latest Event)")
        if alerts:
            scores = alerts[-1]["payload"]["scores"]
            categories = ['Pressure', 'Coriolis Mass', 'Fiber DTS', 'Acoustic', 'Soil Moisture', 
                          'Point Temp', 'Capacitance', 'Corrosion', 'Vibration', 'Std Flow', 'Physics Residual']
            keys = ['pressure', 'coriolis_mass', 'fiber_dts', 'acoustic', 'soil_moisture', 
                    'point_temp', 'capacitance', 'corrosion', 'vibration', 'standard_flow', 'physics_residual']
            values = [scores.get(k, 0) for k in keys]
            
            fig = go.Figure(data=go.Scatterpolar(r=values + [values[0]], theta=categories + [categories[0]],
                fill='toself', fillcolor='rgba(255, 99, 71, 0.2)', line=dict(color='tomato', width=3)))
            fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 1])), showlegend=False, height=500, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(color='white'))
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Waiting for edge alerts to generate radar chart...")

    with col2:
        st.subheader("📄 Latest PHMSA AI Report")
        if alerts:
            latest = alerts[-1]
            st.markdown(f"**Event ID:** `{latest['payload']['event_id']}`")
            st.markdown(f"**Decision:** `{latest['payload']['decision']}`")
            st.divider()
            st.markdown(latest["report"]["report_text"].replace("\n", "  \n"))
        else:
            st.info("Waiting for edge alerts...")

# --- TAB 2: Executive Risk Heatmap ---
with tab_risk:
    st.subheader("Geospatial Dynamic Risk Distribution")
    
    if risk_data:
        # Filter out work order dicts to get pure node data
        nodes = [r for r in risk_data if "node_id" in r]
        df_risk = pd.DataFrame(nodes)
        
        colorscale = [[0.0, 'rgb(0, 200, 83)'], [0.33, 'rgb(255, 235, 59)'], [0.66, 'rgb(255, 152, 0)'], [1.0, 'rgb(244, 67, 54)']]

        fig = go.Figure()
        # Pipeline Route
        if not df_risk.empty:
            fig.add_trace(go.Scattergeo(lon=df_risk['lon'], lat=df_risk['lat'], mode='lines',
                line=dict(width=2, color='rgba(100, 100, 100, 0.5)'), hoverinfo='skip', showlegend=False))
            
            # Risk Nodes
            fig.add_trace(go.Scattergeo(lon=df_risk['lon'], lat=df_risk['lat'], mode='markers+text',
                text=df_risk['node_id'], textposition="top center", textfont=dict(size=8, color='white'),
                marker=dict(size=df_risk['dynamic_risk_index'] / 2 + 5, color=df_risk['dynamic_risk_index'],
                colorscale=colorscale, cmin=0, cmax=100, line=dict(width=1, color='white'), opacity=0.9,
                colorbar=dict(title="Dynamic Risk Index (DRI)", x=1.02, thickness=15)),
                hovertemplate="<b>%{text}</b><br>Risk Tier: %{customdata[0]}<br>DRI: %{customdata[1]}<br>PoF: %{customdata[2]}%<br>CoF: %{customdata[3]}%<extra></extra>",
                customdata=df_risk[['risk_tier', 'dynamic_risk_index', 'pof', 'cof']], name='Sensor Nodes'))

        fig.update_layout(geo=dict(scope='usa', projection=dict(type='albers usa'), showland=True, landcolor='rgb(30, 30, 30)',
            showocean=True, oceancolor='rgb(10, 10, 20)'), paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
            font=dict(color='white'), height=650, margin=dict(l=0, r=0, t=30, b=0))
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No risk data available. Trigger an alert to generate risk assessments.")

# --- TAB 3: Autonomous Actions & EAM ---
with tab_eam:
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🏭 SCADA Shadow Mode Logs")
        if scada_logs:
            for log in reversed(scada_logs[-5:]):
                override_emoji = "⚠️" if log.get("safety_override") else "✅"
                st.markdown(f"**{override_emoji} {log['action']}** -> `{log['target_device']}`")
                st.caption(f"Reasoning: {log['reasoning']} | Status: {log['execution_status']}")
                st.divider()
        else:
            st.info("No SCADA commands executed yet.")

    with col2:
        st.subheader("🛠️ Automated SAP/Maximo Work Orders")
        work_orders = [r for r in risk_data if "work_order" in r]
        if work_orders:
            for wo in reversed(work_orders):
                wo_data = wo["work_order"]
                st.markdown(f"** WO: {wo_data['work_order_id']}** (Priority: {wo_data['priority']})")
                st.markdown(f"**Status:** {wo_data['status']} | **Task List:** {wo_data['task_list']}")
                st.caption(f"Functional Location: {wo_data['functional_location']}")
                st.divider()
        else:
            st.info("No automated work orders generated yet. Trigger a HIGH or CRITICAL risk event.")

# Auto-refresh every 5 seconds
st.markdown("<meta http-equiv='refresh' content='5'>", unsafe_allow_html=True)
