# edge/agents/schemas.py
"""
Shared Data Models for the Multi-Agent Pipeline Architecture.
"""
from dataclasses import dataclass, field
from typing import Dict
from datetime import datetime, timezone

@dataclass
class SitRep:
    """
    Situation Report generated by the Sentinel (Agent 1).
    Describes WHAT is happening, not WHAT TO DO.
    """
    event_id: str
    timestamp: str
    node_id: str
    decision: str  # "SAFE", "ANOMALY_DETECTED", "CRITICAL_FAILURE"
    anomaly_score: float  # 0.0 to 1.0 (Reconstruction error from Transformer)
    primary_modality: str  # Which sensor contributed most to the anomaly
    confidence: float
    scores: Dict[str, float]
    cosmos_context: str = "NORMAL" # Flag from Cosmos Synthetic Generator

@dataclass
class SCADACommand:
    """Final validated command sent to the physical PLCs via the Operator Agent."""
    command_id: str
    timestamp: str
    target_device: str
    action: str
    parameters: Dict[str, float]
    safety_override: bool
    llm_proposal: str
    final_reasoning: str
    execution_status: str = "PENDING"